// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Solidus.Registros.API.Infrastructure.Persistence;

#nullable disable

namespace Solidus.Registros.API.Migrations
{
    [DbContext(typeof(RegistrosDbContext))]
    partial class RegistrosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("registros")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Solidus.Registros.API.Domain.Entities.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChaveIdempotencia")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("chave_idempotencia");

                    b.Property<Guid>("ComercianteId")
                        .HasColumnType("uuid")
                        .HasColumnName("comerciante_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DataCompetencia")
                        .HasColumnType("date")
                        .HasColumnName("data_competencia");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(7)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("ChaveIdempotencia")
                        .IsUnique();

                    b.HasIndex("ComercianteId", "DataCompetencia");

                    b.ToTable("lancamentos", "registros", t =>
                        {
                            t.HasCheckConstraint("ck_lancamentos_valor", "valor > 0");
                        });
                });

            modelBuilder.Entity("Solidus.Registros.API.Infrastructure.Outbox.OutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("PublicadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("publicado_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDENTE'");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CriadoEm");

                    b.ToTable("outbox", "registros");
                });
#pragma warning restore 612, 618
        }
    }
}
