// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Solidus.Posicao.Processor.Infrastructure.Persistence;

#nullable disable

namespace Solidus.Posicao.Processor.Migrations
{
    [DbContext(typeof(PosicaoDbContext))]
    [Migration("20260413161917_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("posicao")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Solidus.Posicao.Processor.Domain.Entities.PosicaoDiaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ComercianteId")
                        .HasColumnType("uuid")
                        .HasColumnName("comerciante_id");

                    b.Property<DateOnly>("DataPosicao")
                        .HasColumnType("date")
                        .HasColumnName("data_posicao");

                    b.Property<decimal>("Saldo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TotalCreditos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_creditos")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TotalDebitos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_debitos")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.HasIndex("ComercianteId", "DataPosicao")
                        .IsUnique();

                    b.ToTable("posicao_diaria", "posicao");
                });

            modelBuilder.Entity("Solidus.Posicao.Processor.Infrastructure.Persistence.EventoProcessado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("ProcessadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("processado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.HasIndex("EventoId")
                        .IsUnique();

                    b.ToTable("eventos_processados", "posicao");
                });
#pragma warning restore 612, 618
        }
    }
}
